// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {ResolverLib} from "../src/ResolverLib.sol";
import {ResolverParityFixtures as Fx} from "./ResolverParityFixtures.sol";

/// @notice THE correctness gate (docs/PLAN.md Workstream B):
///         ResolverLib must reproduce sim/resolver_fixed.py bit-for-bit.
///         Fixtures are generated by sim/gen_parity_fixtures.py.
contract ResolverParityTest is Test {
    uint256 internal constant WAD = 1e18;

    function test_parity_against_python_spec() public pure {
        Fx.Case[] memory cs = Fx.load();
        for (uint256 i = 0; i < cs.length; i++) {
            Fx.Case memory c = cs[i];
            ResolverLib.Outcome memory o = ResolverLib.resolveContest(
                ResolverLib.Contest({
                    committed: c.committed,
                    attackerMod: c.attackerMod,
                    garrison: c.garrison,
                    defenderMod: c.defenderMod
                }),
                ResolverLib.Params({delta: c.delta, gamma: c.gamma, beta: c.beta}),
                c.randomWord
            );
            string memory tag = string.concat("case ", vm.toString(i));
            assertEq(o.attackerWon, c.expWon, string.concat(tag, " won"));
            assertEq(o.pWad, c.expPWad, string.concat(tag, " pWad"));
            assertEq(o.roll, c.expRoll, string.concat(tag, " roll"));
            assertEq(o.toAttacker, c.expToAttacker, string.concat(tag, " toAttacker"));
            assertEq(o.toDefender, c.expToDefender, string.concat(tag, " toDefender"));
            assertEq(o.burned, c.expBurned, string.concat(tag, " burned"));
            assertEq(o.newGarrison, c.expNewGarrison, string.concat(tag, " newGarrison"));
        }
    }

    /// @dev floor-sqrt property over the full uint256 domain — this is what
    ///      guarantees equality with Python's math.isqrt.
    function testFuzz_sqrt_floor(uint256 x) public pure {
        uint256 r = ResolverLib.sqrt(x);
        // r^2 <= x, computed without overflow: r <= 2^128-1 so r*r fits
        assertLe(r * r, x, "sqrt too big");
        // x < (r+1)^2 unless r+1 overflows the 128-bit bound
        if (r < type(uint128).max) {
            uint256 r1 = r + 1;
            // (r+1)^2 may overflow only when x is near uint256 max and
            // r = 2^128-1, excluded above
            assertLt(x, r1 * r1, "sqrt too small");
        }
    }

    /// @dev conservation: value is only ever split between payout and burn —
    ///      an attacker can never extract more than the garrison, a defender
    ///      never more than the commit. Drain analysis, property form.
    function testFuzz_conservation(
        uint96 committed,
        uint96 garrison,
        uint64 aMod,
        uint64 dMod,
        uint256 randomWord
    ) public pure {
        ResolverLib.Outcome memory o = ResolverLib.resolveContest(
            ResolverLib.Contest({
                committed: committed,
                attackerMod: uint256(aMod) % (2 * WAD),
                garrison: garrison,
                defenderMod: uint256(dMod) % (2 * WAD)
            }),
            ResolverLib.Params({delta: 13e17, gamma: 3e17, beta: 3e17}),
            randomWord
        );
        assertLe(o.pWad, WAD, "p > 1");
        if (o.attackerWon) {
            assertEq(o.toAttacker + o.burned, garrison, "win conservation");
            assertEq(o.toDefender, 0, "defender paid on a loss");
            assertEq(o.newGarrison, committed, "garrison != commit");
        } else {
            assertEq(o.toDefender + o.burned, committed, "loss conservation");
            assertEq(o.toAttacker, 0, "attacker paid on a hold");
            assertEq(o.newGarrison, garrison, "garrison changed on a hold");
        }
    }

    /// @dev the empty-tile rule: any positive commit takes an ungarrisoned
    ///      tile with certainty and burns nothing.
    function testFuzz_emptyTile(uint96 committed, uint256 randomWord) public pure {
        vm.assume(committed > 0);
        ResolverLib.Outcome memory o = ResolverLib.resolveContest(
            ResolverLib.Contest(committed, WAD, 0, WAD),
            ResolverLib.Params(13e17, 3e17, 3e17),
            randomWord
        );
        assertTrue(o.attackerWon, "empty tile must fall");
        assertEq(o.pWad, WAD, "p must be 1");
        assertEq(o.burned, 0, "nothing to burn");
    }
}
